# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-10-05 21:56
from __future__ import unicode_literals

from django.db import migrations, models
import salon.models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0003_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to=salon.models.image_folder),
        ),
    ]
