# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-10-05 22:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import salon.models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0004_auto_20191006_0056'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('slug', models.SlugField()),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to=salon.models.image_folder)),
                ('price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('available', models.BooleanField(default=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salon.Brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salon.Category')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salon.Color')),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
