# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-10-05 22:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0005_auto_20191006_0112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='brand',
        ),
    ]
