# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-10-14 12:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0008_auto_20191014_0001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ord',
            name='buying_type',
            field=models.CharField(choices=[('Самовывоз', 'Самовывоз'), ('Доставка', 'Доставка')], default='Самовывоз', max_length=40),
        ),
        migrations.RemoveField(
            model_name='ord',
            name='items',
        ),
        migrations.AddField(
            model_name='ord',
            name='items',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='salon.Cart'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ord',
            name='status',
            field=models.CharField(choices=[('Принят в обработку', 'Принят в обработку'), ('Выполняется', 'Выполняется'), ('Оплачен', 'Оплачен')], default='Принят в обработку', max_length=100),
        ),
    ]
