# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-12-23 21:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0009_auto_20191014_1549'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='color',
        ),
    ]
