# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-12-23 22:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0010_remove_order_color'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Brand',
        ),
        migrations.DeleteModel(
            name='Color',
        ),
    ]
