# Generated by Django 2.2.16 on 2020-09-29 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0011_auto_20191224_0111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ord',
            name='comments',
            field=models.TextField(max_length=1000),
        ),
    ]
