# Generated by Django 2.2.16 on 2020-09-29 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0012_auto_20200929_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ord',
            name='comments',
            field=models.TextField(max_length=3000),
        ),
    ]
