# Generated by Django 2.2.16 on 2020-10-03 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0013_auto_20200929_2230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='qty',
        ),
    ]
