# Generated by Django 2.2.16 on 2020-10-13 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0014_remove_cartitem_qty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ord',
            name='address',
        ),
        migrations.AlterField(
            model_name='ord',
            name='buying_type',
            field=models.CharField(choices=[('Наличные', 'Карта'), ('Наличные', 'Карта')], default='Наличные', max_length=40),
        ),
    ]
